apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretrequests.flowcore.io
spec:
  group: flowcore.io
  names:
    kind: SecretRequest
    plural: secretrequests
    singular: secretrequest
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sourceSecret:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                    - namespace
                destinationSecret:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                    - namespace
              required:
                - sourceSecret
                - destinationSecret
            status:
              type: object
              properties:
                lastSynced:
                  type: string
                resource:
                  type: string
                conditions:
                  description: Represents the latest available observations of a
                    replica set's current state.
                  items:
                    description: ReplicaSetCondition describes the state of a replica
                      set at a certain point.
                    properties:
                      lastTransitionTime:
                        description: The last time the condition transitioned from
                          one status to another.
                        format: date-time
                        type: string
                      message:
                        description: A human readable message indicating details
                          about the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      status:
                        description: Status of the condition, one of True, False,
                          Unknown.
                        type: string
                      type:
                        description: Type of replica set condition.
                        type: string
                    required:
                      - status
                      - type
                    type: object
                  type: array
                observedGeneration:
                  description: ObservedGeneration reflects the generation of the
                    most recently observed ReplicaSet.
                  format: int64
                  type: integer
      subresources:
        status: { }
---
apiVersion: v1
kind: Namespace
metadata:
  name: flowcore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-request-controller
  namespace: flowcore
  labels:
    app: secret-request-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-request-controller
  template:
    metadata:
      labels:
        app: secret-request-controller
        app.kubernetes.io/name: secret-request-controller
    spec:
      containers:
        - name: secret-request-controller
          image: >-
            flowcoreio/flowcore-request-controller:1.0.3
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: secret-request-controller
  namespace: flowcore
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: secret-request-controller
  type: ClusterIP
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: secret-request-controller
  namespace: flowcore
spec:
  generateSelector: true
  parentResource:
    apiVersion: flowcore.io/v1
    resource: secretrequests
  childResources:
    - apiVersion: v1
      resource: secrets
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://secret-request-controller.flowcore:3000/sync
    customize:
      webhook:
        url: http://secret-request-controller.flowcore:3000/customize