name: Build Docker Image

on:
  release:
    types: [ published ]

permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FLOWCORE_MACHINE_GITHUB_TOKEN }}
          submodules: true
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'

      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::305363105399:role/ECRGithubManager
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract package name from package.json
        uses: sergeysova/jq-action@v2
        id: package
        with:
          cmd: 'jq .name package.json -r'

      - name: Show package name
        run: 'echo "version ${{ steps.package.outputs.value }}"'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: flowcoreio/${{ steps.package.outputs.value }}:${{ steps.version.outputs.value }},flowcoreio/${{ steps.package.outputs.value }}:latest